"""Storage codegen CLI.

  python -m codegen --registry registry.json --out ../firmware/generated/storage

Emits five files:

  types.h     — packed nested struct (storage_payload_t) + storage_t
                (header + payload + tail-pad to a 32-byte boundary)
  layout.h    — STORAGE_A/B addresses + sector ids + magic + version
                + sizeof checks for the runtime to consume.
  storage_data.c — declares g_storage (RAM working copy) and the two
                placeholders __storage_a_in_flash / __storage_b_in_flash
                that the linker places into sectors A and B via the .ld
                fragment below.
  storage.ld  — linker fragment: STORAGE_A / STORAGE_B MEMORY entries +
                .storage_a / .storage_b SECTIONS with NOLOAD + size
                ASSERTs.  CM4's main linker script INCLUDEs this file.
  storage_layout.txt — human-readable summary (offsets, sizes, fields)
                for grep-and-go diagnostics.

Hard rules for the schema (validated here, not by JSON-Schema since the
shape is small):
  - field 'type' is one of u8/u16/u32/u64/i8/i16/i32/i64/f32/f64 with
    an optional fixed-array suffix '[N]'.
  - groups + fields are emitted in registry-declaration order (Python
    dicts preserve insertion order); this is what controls the wire
    layout, so reordering fields is a wire-format break.
  - region.size is the per-sector size in bytes (both sectors must be
    the same size — STM32H7 enforces this for sectors in the same
    bank).
"""
from __future__ import annotations

import argparse
import binascii
import json
import sys
from pathlib import Path

PRIM_C = {
    "u8":  "uint8_t",  "i8":  "int8_t",
    "u16": "uint16_t", "i16": "int16_t",
    "u32": "uint32_t", "i32": "int32_t",
    "u64": "uint64_t", "i64": "int64_t",
    "f32": "float",    "f64": "double",
}

PRIM_SIZE = {
    "u8": 1, "i8": 1, "u16": 2, "i16": 2,
    "u32": 4, "i32": 4, "f32": 4,
    "u64": 8, "i64": 8, "f64": 8,
}


def parse_type(type_str: str) -> tuple[str, int | None]:
    """Split 'f32[3]' into ('f32', 3); 'u32' → ('u32', None)."""
    if "[" in type_str:
        prim, rest = type_str.split("[", 1)
        if not rest.endswith("]"):
            raise ValueError(f"malformed array type: {type_str!r}")
        try:
            count = int(rest[:-1])
        except ValueError:
            raise ValueError(f"bad array count in {type_str!r}")
        if count < 1:
            raise ValueError(f"array count must be >= 1 in {type_str!r}")
    else:
        prim, count = type_str, None
    if prim not in PRIM_C:
        raise ValueError(f"unknown primitive in {type_str!r}")
    return prim, count


def field_c_decl(field: dict) -> str:
    prim, count = parse_type(field["type"])
    c = PRIM_C[prim]
    if count is not None:
        return f"{c} {field['name']}[{count}]"
    return f"{c} {field['name']}"


def field_size(field: dict) -> int:
    prim, count = parse_type(field["type"])
    return PRIM_SIZE[prim] * (count if count is not None else 1)


def group_size(group: dict) -> int:
    return sum(field_size(f) for f in group["fields"])


def banner(registry_crc: int) -> str:
    return (
        "// AUTO-GENERATED by storage/codegen — DO NOT EDIT. "
        "Run codegen after editing registry.json.\n"
        f"// Registry CRC32: 0x{registry_crc:08X}\n"
    )


def emit_types(reg: dict, crc: int) -> str:
    """types.h — the actual storage_t typedef."""
    o = [banner(crc), "\n#ifndef STORAGE_GENERATED_TYPES_H\n",
         "#define STORAGE_GENERATED_TYPES_H\n\n",
         "#include <stdint.h>\n\n",
         "/* Header sits at the front of every persistent record. 16 bytes,\n"
         " * naturally aligned. crc32 covers [magic..generation] + payload. */\n",
         "typedef struct __attribute__((packed)) {\n",
         "    uint32_t magic;\n",
         "    uint16_t version;\n",
         "    uint16_t length;        /* payload bytes following the header */\n",
         "    uint32_t generation;    /* monotonic across saves; higher wins */\n",
         "    uint32_t crc32;\n",
         "} storage_header_t;\n",
         "_Static_assert(sizeof(storage_header_t) == 16, "
         "\"storage_header_t must be 16 bytes\");\n\n",
         "/* Payload: groups in registry declaration order, fields in field-\n"
         " * declaration order. Reordering breaks wire layout — version bump\n"
         " * is the only safe edit other than appending. */\n",
         "typedef struct __attribute__((packed)) {\n"]
    for gname, group in reg["groups"].items():
        o.append(f"    /* --- {gname} --- */\n")
        o.append("    struct __attribute__((packed)) {\n")
        for fld in group["fields"]:
            desc = fld.get("description", "")
            if desc:
                o.append(f"        /* {desc} */\n")
            o.append(f"        {field_c_decl(fld)};\n")
        o.append(f"    }} {gname};\n\n")
    payload_size = sum(group_size(g) for g in reg["groups"].values())
    o.append("} storage_payload_t;\n")
    o.append(f"_Static_assert(sizeof(storage_payload_t) == {payload_size}, "
             f"\"storage_payload_t size drift\");\n\n")
    # Pad storage_t up to a 32-byte flashword boundary so a full write
    # always programs whole flashwords. Header (16) + payload + pad.
    raw_total = 16 + payload_size
    padded_total = ((raw_total + 31) // 32) * 32
    pad_bytes = padded_total - raw_total
    o.append("/* Full record = header + payload + pad-to-32B-flashword. */\n")
    o.append("typedef struct __attribute__((packed)) {\n")
    o.append("    storage_header_t  header;\n")
    o.append("    storage_payload_t payload;\n")
    if pad_bytes:
        o.append(f"    uint8_t           _pad[{pad_bytes}];\n")
    o.append("} storage_t;\n")
    o.append(f"_Static_assert(sizeof(storage_t) == {padded_total}, "
             f"\"storage_t total size drift\");\n")
    o.append(f"_Static_assert((sizeof(storage_t) % 32) == 0, "
             f"\"storage_t must be a multiple of the 32-byte flashword\");\n\n")
    o.append("#endif /* STORAGE_GENERATED_TYPES_H */\n")
    return "".join(o)


def emit_layout(reg: dict, crc: int) -> str:
    """layout.h — addresses, magic, version, sector ids."""
    region = reg["region"]
    header = reg["header"]
    o = [banner(crc), "\n#ifndef STORAGE_GENERATED_LAYOUT_H\n",
         "#define STORAGE_GENERATED_LAYOUT_H\n\n",
         "#include <stdint.h>\n\n",
         f"#define STORAGE_REGISTRY_VERSION  {reg['version']}\n",
         f"#define STORAGE_REGISTRY_CRC32    0x{crc:08X}u\n\n",
         f"#define STORAGE_MAGIC             {header['magic']}u  /* 'STOR' little-endian */\n",
         f"#define STORAGE_SCHEMA_VERSION    {reg['version']}\n\n",
         f"#define STORAGE_BANK              {region['bank']}\n",
         f"#define STORAGE_SECTOR_A          {region['sector_a']}\n",
         f"#define STORAGE_SECTOR_B          {region['sector_b']}\n",
         f"#define STORAGE_ORIGIN_A          {region['origin_a']}u\n",
         f"#define STORAGE_ORIGIN_B          {region['origin_b']}u\n",
         f"#define STORAGE_SECTOR_SIZE       {region['size']}u\n\n",
         "/* Convenience pointers cast from the linker-placed symbols. */\n",
         "#include \"generated/storage/types.h\"\n\n",
         "extern const storage_t __storage_a_in_flash;\n",
         "extern const storage_t __storage_b_in_flash;\n\n",
         "#endif /* STORAGE_GENERATED_LAYOUT_H */\n"]
    return "".join(o)


def emit_data_c(reg: dict, crc: int) -> str:
    """storage_data.c — RAM working copy + linker-placed flash placeholders."""
    o = [banner(crc), "\n",
         "#include \"generated/storage/types.h\"\n",
         "#include \"generated/storage/layout.h\"\n\n",
         "/* RAM working copy. lib/storage takes a mutex around modifications\n"
         " * and saves to flash via the deferred storage task. */\n",
         "storage_t g_storage __attribute__((aligned(32)));\n\n",
         "/* Linker-placed flash copies. NOLOAD sections — the firmware image\n"
         " * doesn't carry initial content; lib/storage programs them at runtime\n"
         " * via HAL_FLASH_Program. The 'const' is informational; the actual\n"
         " * mutability comes from the flash unlock dance. */\n",
         "const storage_t __storage_a_in_flash "
         "__attribute__((section(\".storage_a\"), used)) = {0};\n",
         "const storage_t __storage_b_in_flash "
         "__attribute__((section(\".storage_b\"), used)) = {0};\n"]
    return "".join(o)


def emit_ld(reg: dict, crc: int) -> str:
    """Linker fragment — included by CM4's main linker script."""
    region = reg["region"]
    o = ["/*\n",
         f" * AUTO-GENERATED by storage/codegen — DO NOT EDIT.\n",
         f" * Registry CRC32: 0x{crc:08X}\n",
         " *\n",
         " * INCLUDE this from the per-core linker script (e.g. CM4's\n",
         " * stm32h745xx_flash_CM4.ld) to reserve two flash sectors for the\n",
         " * ping-pong storage region. The .storage_a / .storage_b output\n",
         " * sections place the linker-decorated constants from\n",
         " * generated/storage/storage_data.c into sectors A and B.\n",
         " */\n\n",
         "MEMORY\n{\n",
         f"    STORAGE_A (r) : ORIGIN = {region['origin_a']}, LENGTH = {region['size']}\n",
         f"    STORAGE_B (r) : ORIGIN = {region['origin_b']}, LENGTH = {region['size']}\n",
         "}\n\n",
         "SECTIONS\n{\n",
         "    .storage_a (NOLOAD) : ALIGN(32) {\n",
         "        KEEP(*(.storage_a))\n",
         "    } > STORAGE_A\n\n",
         "    .storage_b (NOLOAD) : ALIGN(32) {\n",
         "        KEEP(*(.storage_b))\n",
         "    } > STORAGE_B\n",
         "}\n\n",
         "ASSERT(SIZEOF(.storage_a) <= LENGTH(STORAGE_A),\n",
         "       \"storage_a exceeds sector A — bump sector size or trim groups\");\n",
         "ASSERT(SIZEOF(.storage_b) <= LENGTH(STORAGE_B),\n",
         "       \"storage_b exceeds sector B — bump sector size or trim groups\");\n"]
    return "".join(o)


def emit_layout_txt(reg: dict, crc: int) -> str:
    """Human-readable map."""
    o = [f"Storage registry CRC32: 0x{crc:08X}\n",
         f"Schema version:         {reg['version']}\n\n",
         "Header (16 bytes): magic / version / length / generation / crc32\n\n",
         "Payload layout (offsets from start of payload):\n\n"]
    off = 0
    for gname, group in reg["groups"].items():
        o.append(f"  {gname} @ +{off}\n")
        for fld in group["fields"]:
            sz = field_size(fld)
            o.append(f"    +{off:4d}  {fld['type']:<8} {fld['name']}  ({sz} B)\n")
            off += sz
        o.append("\n")
    payload_size = off
    raw_total = 16 + payload_size
    padded_total = ((raw_total + 31) // 32) * 32
    o.append(f"Payload size:  {payload_size} B\n")
    o.append(f"Record size:   {padded_total} B (header + payload + pad)\n")
    o.append(f"Sector size:   {reg['region']['size']} B "
             f"({100.0 * padded_total / reg['region']['size']:.2f}% used)\n")
    return "".join(o)


def _write_if_changed(path: Path, content: str) -> bool:
    data = content.encode("utf-8")
    if path.is_file() and path.read_bytes() == data:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return True


def main(argv: list[str] | None = None) -> int:
    here = Path(__file__).resolve().parent
    default_registry = here.parent / "registry.json"
    default_out      = (here.parent.parent
                        / "firmware" / "generated" / "storage")

    p = argparse.ArgumentParser(
        prog="storage.codegen",
        description="Generate C headers + linker fragment from registry.json.")
    p.add_argument("--registry", type=Path, default=default_registry)
    p.add_argument("--out",      type=Path, default=default_out)
    p.add_argument("--quiet",    action="store_true")
    args = p.parse_args(argv)

    raw = args.registry.read_bytes()
    crc = binascii.crc32(raw) & 0xFFFFFFFF
    reg = json.loads(raw)

    # Sanity: payload + header + pad must fit in one sector.
    payload = sum(group_size(g) for g in reg["groups"].values())
    record  = ((16 + payload + 31) // 32) * 32
    if record > reg["region"]["size"]:
        print(f"ERROR: record size {record} > sector size "
              f"{reg['region']['size']}", file=sys.stderr)
        return 2

    files = {
        args.out / "types.h":             emit_types(reg, crc),
        args.out / "layout.h":            emit_layout(reg, crc),
        args.out / "storage_data.c":      emit_data_c(reg, crc),
        args.out / "storage.ld":          emit_ld(reg, crc),
        args.out / "storage_layout.txt":  emit_layout_txt(reg, crc),
    }
    changed = []
    for path, content in files.items():
        if _write_if_changed(path, content):
            changed.append(path.name)
    if not args.quiet:
        if changed:
            print(f"wrote {len(changed)} file(s): {', '.join(changed)}")
        else:
            print("up to date — no files changed")
        print(f"registry CRC32: 0x{crc:08X}, record size: {record} B "
              f"({100.0 * record / reg['region']['size']:.2f}% of sector)")
    return 0
