// This file is autogenerated. Changes will be overwritten.
#include "CCHPTZ5OZL/moc_AlarmReceiver.cpp"
#include "CCHPTZ5OZL/moc_CommandSender.cpp"
#include "CCHPTZ5OZL/moc_SensorDataModel.cpp"
#include "CCHPTZ5OZL/moc_SerialBridge.cpp"
