"""Auto-generated from libs/log_records/include/log_records/log_records.h
Do not edit manually. Run tools/sd-log/generate_log_schema.py instead.
"""

from __future__ import annotations

import struct

LOG_SCHEMA_VERSION = 5

TYPE_FORMATS = {'bool': 'B', 'uint8_t': 'B', 'int8_t': 'b', 'uint16_t': 'H', 'int16_t': 'h', 'uint32_t': 'I', 'int32_t': 'i', 'uint64_t': 'Q', 'int64_t': 'q', 'float': 'f', 'double': 'd'}

RECORDS = {

    "flight_header": {
        "id": 16,
        "enum": "LOG_RECORD_TYPE_flight_header",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("uint32_t", "flight_magic"),
            ("uint32_t", "flight_counter"),
        ],
        "format": "<III",
        "struct": struct.Struct("<III"),
    },
    "accel_sample": {
        "id": 1,
        "enum": "LOG_RECORD_TYPE_accel_sample",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("float", "ax_mps2"),
            ("float", "ay_mps2"),
            ("float", "az_mps2"),
        ],
        "format": "<Ifff",
        "struct": struct.Struct("<Ifff"),
    },
    "gyro_sample": {
        "id": 2,
        "enum": "LOG_RECORD_TYPE_gyro_sample",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("float", "gx_rad_s"),
            ("float", "gy_rad_s"),
            ("float", "gz_rad_s"),
        ],
        "format": "<Ifff",
        "struct": struct.Struct("<Ifff"),
    },
    "baro_sample": {
        "id": 3,
        "enum": "LOG_RECORD_TYPE_baro_sample",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("int32_t", "temp_centi"),
            ("int32_t", "pressure_centi"),
            ("uint32_t", "seq"),
        ],
        "format": "<IiiI",
        "struct": struct.Struct("<IiiI"),
    },
    "state_snapshot": {
        "id": 4,
        "enum": "LOG_RECORD_TYPE_state_snapshot",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("float", "q_w"),
            ("float", "q_x"),
            ("float", "q_y"),
            ("float", "q_z"),
            ("float", "altitude_m"),
            ("float", "pos_n_m"),
            ("float", "pos_e_m"),
            ("float", "vel_n_mps"),
            ("float", "vel_e_mps"),
            ("float", "vel_d_mps"),
            ("float", "omega_bx_rad_s"),
            ("float", "omega_by_rad_s"),
            ("float", "omega_bz_rad_s"),
            ("uint8_t", "flight_state"),
            ("uint8_t", "estop_active"),
            ("uint16_t", "reserved"),
        ],
        "format": "<IfffffffffffffBBH",
        "struct": struct.Struct("<IfffffffffffffBBH"),
    },
    "event": {
        "id": 5,
        "enum": "LOG_RECORD_TYPE_event",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("uint16_t", "event_code"),
            ("uint16_t", "data_u16"),
        ],
        "format": "<IHH",
        "struct": struct.Struct("<IHH"),
    },
    "baro2_sample": {
        "id": 6,
        "enum": "LOG_RECORD_TYPE_baro2_sample",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("int32_t", "temp_centi"),
            ("int32_t", "pressure_centi"),
            ("uint32_t", "seq"),
        ],
        "format": "<IiiI",
        "struct": struct.Struct("<IiiI"),
    },
    "gps_fix": {
        "id": 7,
        "enum": "LOG_RECORD_TYPE_gps_fix",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("double", "latitude"),
            ("double", "longitude"),
            ("float", "altitude_msl"),
            ("float", "ground_speed"),
            ("float", "course"),
            ("float", "hdop"),
            ("uint32_t", "time_of_week_ms"),
            ("uint8_t", "fix_quality"),
            ("uint8_t", "num_satellites"),
            ("uint16_t", "reserved"),
        ],
        "format": "<IddffffIBBH",
        "struct": struct.Struct("<IddffffIBBH"),
    },
    "control_output": {
        "id": 8,
        "enum": "LOG_RECORD_TYPE_control_output",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("float", "T_cmd"),
            ("float", "theta_x_cmd"),
            ("float", "theta_y_cmd"),
            ("float", "tau_gim_x"),
            ("float", "tau_gim_y"),
            ("float", "tau_gim_z"),
            ("float", "tau_thrust"),
            ("float", "phi_x"),
            ("float", "phi_y"),
            ("float", "phi_z"),
            ("float", "z_pid_integral"),
            ("float", "z_ref"),
            ("float", "vz_ref"),
        ],
        "format": "<Ifffffffffffff",
        "struct": struct.Struct("<Ifffffffffffff"),
    },
    "calibration": {
        "id": 9,
        "enum": "LOG_RECORD_TYPE_calibration",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("float", "accel_bias_x"),
            ("float", "accel_bias_y"),
            ("float", "accel_bias_z"),
            ("float", "gyro_bias_x"),
            ("float", "gyro_bias_y"),
            ("float", "gyro_bias_z"),
            ("uint16_t", "calibration_samples"),
        ],
        "format": "<IffffffH",
        "struct": struct.Struct("<IffffffH"),
    },
    "pid_gains": {
        "id": 10,
        "enum": "LOG_RECORD_TYPE_pid_gains",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("bool", "has_attitude_kp"),
            ("float", "attitude_kp_x"),
            ("float", "attitude_kp_y"),
            ("float", "attitude_kp_z"),
            ("bool", "has_attitude_kd"),
            ("float", "attitude_kd_x"),
            ("float", "attitude_kd_y"),
            ("float", "attitude_kd_z"),
            ("float", "z_kp"),
            ("float", "z_ki"),
            ("float", "z_kd"),
            ("float", "z_integral_limit"),
        ],
        "format": "<IBfffBfffffff",
        "struct": struct.Struct("<IBfffBfffffff"),
    },
    "reference": {
        "id": 11,
        "enum": "LOG_RECORD_TYPE_reference",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("float", "z_ref"),
            ("float", "vz_ref"),
            ("bool", "has_q_ref"),
            ("float", "q_ref_w"),
            ("float", "q_ref_x"),
            ("float", "q_ref_y"),
            ("float", "q_ref_z"),
        ],
        "format": "<IffBffff",
        "struct": struct.Struct("<IffBffff"),
    },
    "configuration": {
        "id": 12,
        "enum": "LOG_RECORD_TYPE_configuration",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("float", "mass"),
            ("float", "T_min"),
            ("float", "T_max"),
            ("float", "theta_min"),
            ("float", "theta_max"),
        ],
        "format": "<Ifffff",
        "struct": struct.Struct("<Ifffff"),
    },
    "radio_telemetry": {
        "id": 13,
        "enum": "LOG_RECORD_TYPE_radio_telemetry",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("uint32_t", "timestamp_ms"),
            ("float", "position_x"),
            ("float", "position_y"),
            ("float", "position_z"),
            ("float", "velocity_x"),
            ("float", "velocity_y"),
            ("float", "velocity_z"),
            ("float", "attitude_w"),
            ("float", "attitude_x"),
            ("float", "attitude_y"),
            ("float", "attitude_z"),
            ("float", "angular_rate_x"),
            ("float", "angular_rate_y"),
            ("float", "angular_rate_z"),
            ("float", "thrust_cmd"),
            ("float", "gimbal_x"),
            ("float", "gimbal_y"),
            ("uint8_t", "flight_state"),
            ("uint8_t", "reserved1"),
            ("uint16_t", "reserved2"),
        ],
        "format": "<IIffffffffffffffffBBH",
        "struct": struct.Struct("<IIffffffffffffffffBBH"),
    },
    "radio_status": {
        "id": 14,
        "enum": "LOG_RECORD_TYPE_radio_status",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("uint32_t", "timestamp_ms"),
            ("uint32_t", "uptime_ms"),
            ("uint32_t", "radio_tx_count"),
            ("uint32_t", "radio_rx_count"),
            ("uint32_t", "cmd_rx_count"),
            ("uint8_t", "flight_state"),
            ("bool", "accel_ok"),
            ("bool", "gyro_ok"),
            ("bool", "baro1_ok"),
            ("bool", "baro2_ok"),
            ("bool", "gps_connected"),
            ("uint16_t", "reserved"),
        ],
        "format": "<IIIIIIBBBBBBH",
        "struct": struct.Struct("<IIIIIIBBBBBBH"),
    },
    "trace_batch": {
        "id": 32,
        "enum": "LOG_RECORD_TYPE_trace_batch",
        "fields": [
            ("uint32_t", "base_timestamp_us"),
            ("uint8_t", "event_count"),
            ("uint8_t", "reserved1"),
            ("uint16_t", "reserved2"),
        ],
        "format": "<IBBH",
        "struct": struct.Struct("<IBBH"),
    },
    "trace_overflow": {
        "id": 33,
        "enum": "LOG_RECORD_TYPE_trace_overflow",
        "fields": [
            ("uint32_t", "timestamp_us"),
            ("uint32_t", "dropped_count"),
        ],
        "format": "<II",
        "struct": struct.Struct("<II"),
    },
}

MAX_RECORD_SIZE = max(rec['struct'].size for rec in RECORDS.values())
