#ifndef LIB_DSHOT_PROTOCOL_BDSHOT_H
#define LIB_DSHOT_PROTOCOL_BDSHOT_H

#define BDSHOT_TELEMETRY_GCR_BITS (20)
#define BDSHOT_TELEMETRY_GCR_MASK (0x000FFFFF)

#define BDSHOT_TELEMETRY_WIRE_BITS (21)

#define BDSHOT_ERPM_EXPONENT_MASK  (0xE000)
#define BDSHOT_ERPM_EXPONENT_BITS  (3)
#define BDSHOT_ERPM_EXPONENT_SHIFT (13)

#define BDSHOT_ERPM_MANTISSA_MASK  (0x1FF0)
#define BDSHOT_ERPM_MANTISSA_BITS  (9)
#define BDSHOT_ERPM_MANTISSA_SHIFT (4)

#endif // LIB_DSHOT_PROTOCOL_BDSHOT_H
