name: Firmware Libraries Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'embedded-software/firmware/libs/state_estimation/**'
      - 'embedded-software/firmware/libs/controls/**'
      - 'embedded-software/firmware/libs/unity/**'
  pull_request:
    paths:
      - 'embedded-software/firmware/libs/state_estimation/**'
      - 'embedded-software/firmware/libs/controls/**'
      - 'embedded-software/firmware/libs/unity/**'

jobs:
  test-state-estimation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        working-directory: embedded-software/firmware/libs/state_estimation/tests
        run: cmake -B build

      - name: Build
        working-directory: embedded-software/firmware/libs/state_estimation/tests
        run: cmake --build build

      - name: Run tests
        working-directory: embedded-software/firmware/libs/state_estimation/tests
        run: ctest --test-dir build --output-on-failure

  test-controls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        working-directory: embedded-software/firmware/libs/controls/tests
        run: cmake -B build

      - name: Build
        working-directory: embedded-software/firmware/libs/controls/tests
        run: cmake --build build

      - name: Run tests
        working-directory: embedded-software/firmware/libs/controls/tests
        run: ctest --test-dir build --output-on-failure
