name: Ground Station

on:
  workflow_dispatch:
  push:
    paths:
      - 'embedded-software/ground-station/**'
      - 'embedded-software/libs/rocket-protocol/**'
  pull_request:
    paths:
      - 'embedded-software/ground-station/**'
      - 'embedded-software/libs/rocket-protocol/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.*'
          modules: 'qtserialport qtquick3d qtshadertools'

      - name: Configure CMake
        working-directory: embedded-software/ground-station
        run: cmake -B build

      - name: Build
        working-directory: embedded-software/ground-station
        run: cmake --build build
