"""Shared helpers for emitters: file banner, sorted iteration."""

from __future__ import annotations

from typing import Any


def banner(crc32: int) -> str:
    return (
        "// AUTO-GENERATED by messages/codegen — DO NOT EDIT. "
        "Run codegen after editing registry.json.\n"
        f"// Registry CRC32: 0x{crc32:08X}\n"
    )


def channels_sorted(registry: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    """Channels in ascending channel_id order (deterministic)."""
    items = list(registry["channels"].items())
    items.sort(key=lambda kv: kv[1]["channel_id"])
    return items


def modules_sorted(registry: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    """Modules in ascending module_id order."""
    items = list(registry["modules"].items())
    items.sort(key=lambda kv: kv[1]["module_id"])
    return items


def messages_sorted(module: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    items = list((module.get("messages") or {}).items())
    items.sort(key=lambda kv: kv[1]["msg_id"])
    return items


def errors_sorted(module: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    items = list((module.get("errors") or {}).items())
    items.sort(key=lambda kv: kv[1]["code"])
    return items
