#include "clamp.h"
#include "controls/flight_controller.h"
#include "controls/pid.h"
#include "state_estimation/state.h"
#include <math.h>
#include <float.h>
#include <string.h>

#define AXIS_ERR_EPSILON 1e-9f

#define PHI_SETPOINT_X 0.0f
#define PHI_SETPOINT_Y 0.0f
#define PHI_SETPOINT_Z 0.0f

// Should be set throught ground control station
#define TORQUE_THRUST_MIN -0.5f // Min torque that can be generated by differential props (Nm)
#define TORQUE_THRUST_MAX 0.5f  // Max torque that can be generated by differential props (Nm)

// ====

static pid_controller_t torque_x_pid;
static pid_controller_t torque_y_pid;
static pid_controller_t torque_z_pid;
static pid_controller_t z_pid;

static bool is_initialized = false;
static float thrust_dir[3] = {0.0f, 0.0f, -1.0f}; // Thrust direction
static float thrust_mag = 0.0f;

// ====

// Equation 1: Axis-Angle Error Calcuation
static inline void compute_axis_angle_err(const quaternion_t *q_ref,
                                          const quaternion_t *q_meas,
                                          float phi[3])
{
    // Quaternion error calculation
    quaternion_t q_err;
    quaternion_t q_meas_conj;

    quaternion_conjugate(q_meas, &q_meas_conj);
    quaternion_multiply(q_ref, &q_meas_conj, &q_err);

    // flip is w < 0 to ensure shortest rotation
    if (q_err.w < 0.0f)
    {
        q_err.w = -q_err.w;
        q_err.x = -q_err.x;
        q_err.y = -q_err.y;
        q_err.z = -q_err.z;
    }

    // Axis-angle error calculation
    float v_x = q_err.x, v_y = q_err.y, v_z = q_err.z;
    float v_mag = sqrtf(v_x * v_x + v_y * v_y + v_z * v_z);

    if (v_mag < AXIS_ERR_EPSILON)
    {
        // If the error is very small, set phi to zero to avoid numerical issues
        phi[0] = 0.0f;
        phi[1] = 0.0f;
        phi[2] = 0.0f;
        return;
    }

    float angle = 2.0f * atan2f(v_mag, q_err.w);
    float scale = angle / v_mag;

    phi[0] = scale * v_x;
    phi[1] = scale * v_y;
    phi[2] = scale * v_z;
}

// Equation 2: Torque Command Calculation
static inline void update_and_get_torque_pid(const quaternion_t *q_ref,
                                             const quaternion_t *q_meas,
                                             const float dt_s,
                                             float torque_cmd[3])
{
    float phi[3];
    compute_axis_angle_err(q_ref, q_meas, phi);

    // Compute torque commands using PID controllers
    torque_cmd[0] = pid_compute(&torque_x_pid, PHI_SETPOINT_X, phi[0], dt_s);
    torque_cmd[1] = pid_compute(&torque_y_pid, PHI_SETPOINT_Y, phi[1], dt_s);
    torque_cmd[2] = pid_compute(&torque_z_pid, PHI_SETPOINT_Z, phi[2], dt_s);
}

// Equation 3: Torque Decomposiition into Thrust and Gimbal Commands
static inline void decompose_torque(const float torque_cmd[3], float torque_gimbal[3], float* torque_thrust_mag)
{
    *torque_thrust_mag = clamp_float(
        vec3_dot(torque_cmd, thrust_dir),
        TORQUE_THRUST_MIN,
        TORQUE_THRUST_MAX);

    torque_thrust[0] = *torque_thrust_mag * thrust_dir[0];
    torque_thrust[1] = *torque_thrust_mag * thrust_dir[1];
    torque_thrust[2] = *torque_thrust_mag * thrust_dir[2];

    torque_gimbal[0] = torque_cmd[0] - torque_thrust[0];
    torque_gimbal[1] = torque_cmd[1] - torque_thrust[1];
    torque_gimbal[2] = torque_cmd[2] - torque_thrust[2];
}

static inline void compute_gimbal_control() 
{

}


static void compute_thrust_control(const state_t *state,
                                   const flight_controller_ref_t *ref,
                                   const flight_controller_config_t *config,
                                   control_output_t *out,
                                   float dt_s)
{
}

// ====

void flight_controller_init(const flight_controller_config_t *config)
{
    if (config == NULL)
        return;

    // initialize thrust pid
    const flight_controller_thrust_config_t *tcfg = &config->thrust;
    pid_init(&z_pid,
             tcfg->kp, tcfg->ki, tcfg->kd,
             tcfg->integral_limit,
             tcfg->a_z_min, tcfg->a_z_max);

    // initialize torque pids
    const flight_controller_attitude_config_t *acfg = &config->attitude;
    pid_init(&torque_x_pid,
             acfg->Kp[0][0], 0, acfg->Kd[0][0],
             FLT_MAX, -FLT_MIN, FLT_MAX);
    pid_init(&torque_y_pid,
             acfg->Kp[1][1], 0, acfg->Kd[1][1],
             FLT_MAX, -FLT_MIN, FLT_MAX);
    pid_init(&torque_z_pid,
             acfg->Kp[2][2], 0, acfg->Kd[2][2],
             FLT_MAX, -FLT_MIN, FLT_MAX);

    is_initialized = true;

    // Set thrust direction from config
    thrust_dir[0] = config->allocation.thrust_dir[0];
    thrust_dir[1] = config->allocation.thrust_dir[1];
    thrust_dir[2] = config->allocation.thrust_dir[2];

    thrust_mag = 0.0f;
}

void flight_controller_run(const state_t *state,
                           const flight_controller_ref_t *ref,
                           const flight_controller_config_t *config,
                           control_output_t *out,
                           float dt_s)
{
    if (!state || !ref || !config || !out)
        return;

    const flight_controller_thrust_config_t *tcfg = &config->thrust;
    const flight_controller_gimbal_config_t *gcfg = &config->gimbal;

    // Module 1: Torque
    float torque_cmd[3];
    update_and_get_torque_pid(&ref->attitude, &state->attitude, dt_s, torque_cmd);

    float torque_thrust_mag;
    float torque_gimbal[3];
    decompose_torque(torque_cmd, torque_gimbal, &torque_thrust_mag);

    

    // TODO: rewrite the functions first
    

    // TODO: rewrite the functions first
}

void flight_controller_reset(void)
{
    pid_reset(&torque_x_pid);
    pid_reset(&torque_y_pid);
    pid_reset(&torque_z_pid);
    pid_reset(&z_pid);
}
